#!/bin/bash

set -euo pipefail

# Use gpiod instead of the obsolete sysfs GPIO interface.
# In October 2025, the Raspberry Pi OS was updated from Bookworm to Trixie. The libgpiod library in Trixie has been upgraded to version 2.2.1.
# The syntax of the gpioset command has changed, so harry@geekworm.com updated this script.
# Refer to https://libgpiod.readthedocs.io/en/latest/gpio_tools.html#examples

readonly GPIOCHIP=0
readonly BUTTON=26

# gpioset -z -c $GPIOCHIP $BUTTON=1
gpioset -c $GPIOCHIP -p 2s $BUTTON=1

# Restore GPIO
# This step is necessary, otherwise you will have to press the onboard button twice to turn on the device, and the same applies to the AUTO ON function.
#gpioset -c $GPIOCHIP -t0 $BUTTON=0
gpioset -z -c $GPIOCHIP $BUTTON=0
