#!/bin/bash
lib="${wd}/usr/lib"
python="${lib}/python3/dist-packages/PowerSupplyServerConnection"
psmodule="${python}/PowerSupplyServerConnection.py"
sed -i "s,from WireAnalogDigitalConversion,from PowerSupplyServerConnection.WireAnalogDigitalConversion," "${psmodule}"
sed -i "s,/home/mu2e/LVHVBox/commands.h,/etc/mu2e-tracker-lvhv-tools/commands.h," "${psmodule}"
echo 'from PowerSupplyServerConnection.PowerSupplyServerConnection import PowerSupplyServerConnection' >"${python}/__init__.py"
